common: &default
  events:
    -
      begins_at: '2016-04-20 00:00:00 +0800'
      ends_at: '2016-04-25 23:59:59 +0800'
      category_keys:
        - 'mug'
        - 'canvas'
        - 'pillow'
      coupon_ids:
        - 434413
        - 409390
    -
      begins_at: '2016-05-26 00:00:00 +0800'
      ends_at: '2099-12-31 23:59:59 +0800'
      region:
        - 'china'
      product_keys:
        - 'iphone_6_matte_cases_kr'
        - 'iphone_6plus_matte_cases_kr'
        - 'iphone_6_cases'
        - 'iphone_6plus_cases'
      coupon_ids:
        - 453738
        - 467315
        - 509020
        - 559242
        - 371414
        - 434417
        - 435048
        - 435149
        - 453738
        - 453757
        - 466857
        - 467010
        - 467263
        - 467315
        - 472433
        - 508999
        - 509020
        - 524027
        - 543927
        - 546928
        - 554133
        - 557134
        - 559235
        - 559242
        - 559245
        - 559296
        - 559327
        - 559421
        - 559442
        - 597216
        - 631585
        - 634086
        - 636587
        - 639088
        - 641589
        - 641790
        - 644291
        - 608251
        - 608250
        - 554132
        - 508977
        - 261921
    -
      begins_at: '2016-07-05 00:00:00 +0800'
      ends_at: '2099-07-05 23:59:59 +0800'
      category_keys:
        - 'mug'
      coupon_ids:
        - 803527
      region:
        - 'china'

production:
  <<: *default

development:
  <<: *default

staging:
  <<: *default

test:
