code:
  0: "交易核准"
  1: "請查詢銀行"
  2: "請查詢銀行"
  3: "無效之特店"
  4: "沒收卡"
  5: "拒絕交易"
  6: "錯誤"
  7: "沒收卡"
  12: "無效交易"
  13: "不符發卡行設定之限額"
  14: "卡號不存在"
  15: "發卡行不存在"
  19: "再輸入之交易型態"
  21: "無法將原先之交易取消"
  25: "登錄於 VISA 停掛系統之資料無法接受"
  28: "查詢或更新登錄於 VISA，停掛系統之資料無法接受"
  30: "格式錯誤"
  33: "過期卡"
  41: "遺失卡"
  43: "失竊卡，予以沒收"
  51: "可用餘額不足"
  54: "過期卡"
  55: PIN 不正確
  56: "發卡行未提供持卡人該項 交易之功能"
  57: "發卡行未提供持卡人該項 交易之功能"
  61: "超過發卡行設定於 VISA，系統活動檔之限額"
  62: "該卡片發卡行已限制"
  65: "超過發卡行設定於 VISA，系統活動檔之限次"
  75: "PIN 輸入錯誤超過次數"
  80: "交易日期不符"
  81: "PIN 密碼或 CVV 值不正確"
  82: "CVV 不正確"
  85: "經查證後,卡片並無錯"
  91: "發卡行無法接受或處理該訊息"
  93:  "交易無法完成 ,不允許之交易"
  94: "重覆交易"
  96: "系統功能異常"
  99: "線路繁忙"
  IE: "ID 錯誤"
